### PR TITLE
Stop breaking of protected blocks

### PR DESCRIPTION
**Pull request by duzos**
Means their data doesnt get lost as they can't be broken in the first place.

### CODE REVIEW

**Comment by Jeryn99** [comment]
Have you tested this in instances where the player does not break the block?

**Comment by duzos** [comment]
like with the configurator ?
yeah it worked with that
what other instances are there to test

**Comment by Jeryn99** [comment]
if you test /setblock (or whatever it is nowadays) and it works, I will merge

**Comment by duzos** [comment]
works

**Pull request merged**
