### PR TITLE
Shell/fullcoral implementation

### PR DESCRIPTION
**Pull request by Magicmaan**
mentions error on startup:
Caused by: java.util.NoSuchElementException: Can't find part door_closed
	at net.minecraft.client.model.geom.ModelPart.getChild(ModelPart.java:89) ~[minecraft-project-@fabric-merged-named.jar:?]
	at whocraft.tardis_refined.client.model.blockentity.door.GrowthDoorModel.<init>(GrowthDoorModel.java:26) ~[26815520406378570.jar:?]
	at whocraft.tardis_refined.client.renderer.blockentity.door.GlobalDoorRenderer.<init>(GlobalDoorRenderer.java:34) ~[26815520406378570.jar:?]

Doesn't allow game to get to main screen as it constantly reloads.

### CODE REVIEW

**Comment by Magicmaan** [comment]
image

**Comment by Magicmaan** [comment]
ready for commit

**Comment by CommandrMoose** [comment]
image
The interior door seems to be broken

**Review by Suff99 — APPROVED** [review]
All issues fixed, looking good

**Pull request merged**
