### PR TITLE
Implement Dimensonal Travel

### PR DESCRIPTION
**Pull request by thejudge156**
TARDIS's are meant to be able to travel to different planets, this PR allows said TARDIS to do so.

Should be completely compatible with modded dimensions that are registered at server startup. I am looking for feedback on the placement for controls and such.

### CODE REVIEW

**Comment by CommandrMoose** [comment]
This PR looks great!

However, we cannot accept it at this time. Dimensional travel has been deliberately not included as it is tied to an upcoming feature.

**Comment by thejudge156** [comment]
Shall I close this PR?

**Comment by thejudge156** [comment]
Didn't see the edit 😄

**Comment by CommandrMoose** [comment]
Closing this PR. It has been used as a base for upcoming commits relating to dimensions. Thank you for this!

**Pull request closed without merging**
