### PR TITLE
Move demat and remat anim ticks to client tick instead of world tick.

### PR DESCRIPTION
**Pull request by thejudge156**
This is to prevent a bug with IP that leads to the demat and remat anim going at 2x speed.

### CODE REVIEW

**Comment by thejudge156** [comment]
Fixes half of #134

**Review by Suff99 — CHANGES_REQUESTED** [review]
The only issue I really have with this, is that you could unify the logic into one method that's called by the separated events

**Comment by thejudge156** [comment]
> The only issue I really have with this, is that you could unify the logic into one method that's called by the separated events

I fixed that, if you could take a look that would be good.

**Review by 50ap5ud5 — APPROVED** [review]
LGTM, thanks Judge!

**Review by Suff99 — APPROVED** [review]

**Pull request merged**
