### PR TITLE
Land on any block that prevents movement

### LINKED ISSUE #42: [BUG] TARDIS can land on non-solid blocks
**Describe the bug**
TARDIS can land on tall grass and other non-solid blocks

**To Reproduce**
1. Find a piece of grass
2. Get the coordinates of the grass block
3. Takeoff and Land

**Expected behavior**
Replace the grass or land around it.

**Screenshots**

**Platform:**
 - Game version: 1.19.2
 - Platform: Fabric

### PR DESCRIPTION
**Pull request by thejudge156**
Makes the landing mechanism land on any block that prevents movement.

### CODE REVIEW

**Comment by thejudge156** [comment]
Github does not want to link the issue :/

**Comment by thejudge156** [comment]
Whatever I give up lol

**Comment by Suff99** [comment]
Looks good, will also need @CommandrMoose's review

**Review by Suff99 — APPROVED** [review]
Lookin good

**Comment by CommandrMoose** [comment]
Looking good. However for blocks like redstone that could be problematic. Possibly make the block be broken before.

**Comment by CommandrMoose** [comment]
Fix the merge and we'll be good to go!

**Comment by CommandrMoose** [comment]
Looks great!

**Pull request merged**
